requires 'Carton';
requires 'Starman';
requires 'Mojolicious';
requires 'DBI';
requires 'Acme::FizzBuzz';
requires 'CGI::PSGI';
requires 'CGI::Parse::PSGI';
requires 'CGI::Compile';
requires 'XMLRPC::Transport::HTTP::Plack';
